export const NEORUEGEN = {};

NEORUEGEN.attributes = {
  koerper: 'NEORUEGEN.Attribute.Koerper',
  verstand: 'NEORUEGEN.Attribute.Verstand',
  schneid: 'NEORUEGEN.Attribute.Schneid',
};

NEORUEGEN.skills = {
  athletik: 'NEORUEGEN.Skill.Athletik',
  heimlichkeit: 'NEORUEGEN.Skill.Heimlichkeit',
  wahrnehmung: 'NEORUEGEN.Skill.Wahrnehmung',
  ueberzeugen: 'NEORUEGEN.Skill.Ueberzeugen',
  wissen: 'NEORUEGEN.Skill.Wissen',
  technik: 'NEORUEGEN.Skill.Technik',
  ueberleben: 'NEORUEGEN.Skill.Ueberleben',
  fahren: 'NEORUEGEN.Skill.Fahren',
  nahkampf: 'NEORUEGEN.Skill.Nahkampf',
  schusswaffen: 'NEORUEGEN.Skill.Schusswaffen',
  taktik: 'NEORUEGEN.Skill.Taktik',
  schwereWaffen: 'NEORUEGEN.Skill.SchwereWaffen',
  panzerung: 'NEORUEGEN.Skill.Panzerung',
  einschuechtern: 'NEORUEGEN.Skill.Einschuechtern',
  hacking: 'NEORUEGEN.Skill.Hacking',
  netzwerke: 'NEORUEGEN.Skill.Netzwerke',
  elektronik: 'NEORUEGEN.Skill.Elektronik',
  drohnensteuerung: 'NEORUEGEN.Skill.Drohnensteuerung',
  sensorik: 'NEORUEGEN.Skill.Sensorik',
  biotech: 'NEORUEGEN.Skill.Biotech',
  chemie: 'NEORUEGEN.Skill.Chemie',
  verhandeln: 'NEORUEGEN.Skill.Verhandeln',
  taeuschen: 'NEORUEGEN.Skill.Taeuschen',
  stil: 'NEORUEGEN.Skill.Stil',
  sicherheitssysteme: 'NEORUEGEN.Skill.Sicherheitssysteme',
  verkleidung: 'NEORUEGEN.Skill.Verkleidung',
  konstruktion: 'NEORUEGEN.Skill.Konstruktion',
  programmierung: 'NEORUEGEN.Skill.Programmierung',
  navigation: 'NEORUEGEN.Skill.Navigation',
  schmuggel: 'NEORUEGEN.Skill.Schmuggel',
  handel: 'NEORUEGEN.Skill.Handel',
  buerokratie: 'NEORUEGEN.Skill.Buerokratie',
};
